name: Build and deploy Node.js project to Azure Function App - skd-function-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 'Install Dependencies'
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: bun install

      - name: 'Build Project'
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: bun run tsc

      - name: 'Zip Artifact'
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: zip -r functionapp.zip .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: 'skd-function-prod'
          package: './functionapp.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SKD_FUNCTION }}
          scm-do-build-during-deployment: false