name: Build and deploy Node.js project to Azure Function App - skd-function-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your web app project
  NODE_VERSION: '20.x' # Node.js version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install Dependencies'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      - name: 'Build Project'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm run build --if-present
          popd

      - name: 'Zip Artifact'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          zip -r functionapp.zip .
          popd

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: 'skd-function-prod'
          package: './functionapp.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SKD_FUNCTION }}
          scm-do-build-during-deployment: false
